### ISSUE TITLE
[featureRequest]Tab 切换栏支持自定义 className

### ISSUE THREAD

**Issue by owensss** [uxcore/uxcore-tabs#17]
RcTabs 的 className 写死了. 希望能自定义 className

**Comment by eternalsky** [comment]
并没有写死，className 是会传进去，请再试下。

**Comment by owensss** [comment]
@eternalsky  嗯嗯表达有误, 是

```role="tab"``` ```class="kuma-tab-tab"``` 的这个东西. Tab 切换栏. 可以往上面加事件, 但是没法给它加自定义 class

**Comment by eternalsky** [comment]
https://github.com/uxcore/uxcore-tabs/blob/master/src/Tabs.jsx#L39 目前可以定义顶级类名，所有的样式定制都可以基于这个顶级类名来进行。

**Comment by owensss** [comment]
@eternalsky 不想定义样式, 想给它加 spm 码记录 onChange 打点 (

不想用在 onChange 事件里发 ajax 请求的方式打点, 因为无法在界面上直接看到打点结果.

想通过 className 找到对应对象并加上相关 gostr 属性, 但是如果不能给加 className 的话就只能 jquery 一层层往下找下去, 然后通过标题正文映射到标题的 key 了. 这个方法比较暴力, 容易受正文更改的影响.

另外给 Tab 栏加 spm 码记录切换 Tab 打点应该不会是个很罕见的需求.

**Comment by eternalsky** [comment]
spm 打点，那么需要可以传 className 的地方就太多了，对于组件来说不现实，目前有两个方案供你参考，一个可以在 <TabPane> 的 tab 属性上做文章，一个可以在 <TabPane> 传入的内容（children 属性里做文章），你的目标其实也是为了区分那个 tab 下的内容的热点吧。

**Comment by owensss** [comment]
不是, 就是为了记录 tab 本身切换的打点

我和我们前端小哥再商量一下咋整吧. (我仍然觉得这个表头栏加 className 是有必要的.

**Comment by eternalsky** [comment]
@owensss 传入的 tab，也可以把你对应的 spm 打点信息传进去的，包一层 span 例如，tab 是支持传 jsx 的。
