### ISSUE TITLE
能否实现浏览器窗口大小改变时，选中的tab上方的橙色横线的宽度不变

### ISSUE THREAD

**Issue by yanba** [uxcore/uxcore-tabs#9]

**Comment by yanba** [comment]
![tab](https://cloud.githubusercontent.com/assets/19427301/15416398/9804c380-1e7d-11e6-990a-af6fc76b9668.png)

**Comment by macisi** [comment]
不是很明白，窗口尺寸变化不会影响tab尺寸

**Comment by eternalsky** [comment]
@macisi 指的是上面那条可以动的线，如果缩小窗体大小的话，好像会缩小
